### ISSUE TITLE
ci: use path filter to run only ethereum tests when possible

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#253]
## Why

The current CI runs always all the tests (approx. 60min) which is noth slow and uselss.

## What

Runs the tests in `src/` only if the directory has changes

## How

Use a path filter step like

````
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
      ethereum: ${{ steps.filter.outputs.ethereum }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'cairo/src/**'
            ethereum:
              - 'cairo/ethereum/**'
```

and don't run the tests in `tests/src` is this directory has not change `pytest --ignore=(cairo/)src`
